version: '2'
services:
  master:
    image: stage:latest
    container_name: master
    network_mode: host
    command: "/bin/bash -c 'source /catkin_ws/devel/setup.bash && roslaunch robots_stage stage.launch'"

  testit_dtron:
    image: testit_dtron:tron_dev
    container_name: testit_dtron
    network_mode: host
    volumes:
      - ~/models:/catkin_ws/src/testit_dtron/testit_dtron/dtron/models
    command: "/bin/bash -c '/catkin_ws/spread/sbin/spread -n localhost & (sleep 8 && source /catkin_ws/devel/setup.bash && roslaunch testit_dtron run_with_load_params.launch) & (sleep 16 && source /catkin_ws/devel/setup.bash && rosrun testit_dtron run_dtron_test.sh $$(rospack find testit_dtron)/dtron/example.xml)'"
    depends_on:
      - master
